//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITFinalConsumeWCFService.DBService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ITFinalWCFService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DBService.IDBService")]
    public interface IDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetData", ReplyAction="http://tempuri.org/IDBService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetData", ReplyAction="http://tempuri.org/IDBService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDBService/GetDataUsingDataContractResponse")]
        ITFinalConsumeWCFService.DBService.CompositeType GetDataUsingDataContract(ITFinalConsumeWCFService.DBService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IDBService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ITFinalConsumeWCFService.DBService.CompositeType> GetDataUsingDataContractAsync(ITFinalConsumeWCFService.DBService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetDataSet", ReplyAction="http://tempuri.org/IDBService/GetDataSetResponse")]
        System.Data.DataSet GetDataSet(string connString, string queryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetDataSet", ReplyAction="http://tempuri.org/IDBService/GetDataSetResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetAsync(string connString, string queryString);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetItemDetailAll", ReplyAction="http://tempuri.org/IDBService/GetItemDetailAllResponse")]
        System.Data.DataTable GetItemDetailAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDBService/GetItemDetailAll", ReplyAction="http://tempuri.org/IDBService/GetItemDetailAllResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetItemDetailAllAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDBServiceChannel : ITFinalConsumeWCFService.DBService.IDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBServiceClient : System.ServiceModel.ClientBase<ITFinalConsumeWCFService.DBService.IDBService>, ITFinalConsumeWCFService.DBService.IDBService {
        
        public DBServiceClient() {
        }
        
        public DBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ITFinalConsumeWCFService.DBService.CompositeType GetDataUsingDataContract(ITFinalConsumeWCFService.DBService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ITFinalConsumeWCFService.DBService.CompositeType> GetDataUsingDataContractAsync(ITFinalConsumeWCFService.DBService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Data.DataSet GetDataSet(string connString, string queryString) {
            return base.Channel.GetDataSet(connString, queryString);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataSetAsync(string connString, string queryString) {
            return base.Channel.GetDataSetAsync(connString, queryString);
        }
        
        public System.Data.DataTable GetItemDetailAll() {
            return base.Channel.GetItemDetailAll();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetItemDetailAllAsync() {
            return base.Channel.GetItemDetailAllAsync();
        }
    }
}
