//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITFinalConsumeWCFService.ITFinalAjaxDBService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ItemDetail", Namespace="http://schemas.datacontract.org/2004/07/ITFinalWCFService.Classes")]
    [System.SerializableAttribute()]
    public partial class ItemDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ItemIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ItemMFDYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemMakeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemPurchasedOnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemSpecificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float ItemUnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemId {
            get {
                return this.ItemIdField;
            }
            set {
                if ((this.ItemIdField.Equals(value) != true)) {
                    this.ItemIdField = value;
                    this.RaisePropertyChanged("ItemId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short ItemMFDYear {
            get {
                return this.ItemMFDYearField;
            }
            set {
                if ((this.ItemMFDYearField.Equals(value) != true)) {
                    this.ItemMFDYearField = value;
                    this.RaisePropertyChanged("ItemMFDYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemMake {
            get {
                return this.ItemMakeField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemMakeField, value) != true)) {
                    this.ItemMakeField = value;
                    this.RaisePropertyChanged("ItemMake");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemPurchasedOn {
            get {
                return this.ItemPurchasedOnField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemPurchasedOnField, value) != true)) {
                    this.ItemPurchasedOnField = value;
                    this.RaisePropertyChanged("ItemPurchasedOn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemSpecification {
            get {
                return this.ItemSpecificationField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemSpecificationField, value) != true)) {
                    this.ItemSpecificationField = value;
                    this.RaisePropertyChanged("ItemSpecification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float ItemUnitPrice {
            get {
                return this.ItemUnitPriceField;
            }
            set {
                if ((this.ItemUnitPriceField.Equals(value) != true)) {
                    this.ItemUnitPriceField = value;
                    this.RaisePropertyChanged("ItemUnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ITFinalAjaxDBService.ITFinalAjaxDBService")]
    public interface ITFinalAjaxDBService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ITFinalAjaxDBService/DoWork", ReplyAction="urn:ITFinalAjaxDBService/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ITFinalAjaxDBService/DoWork", ReplyAction="urn:ITFinalAjaxDBService/DoWorkResponse")]
        System.Threading.Tasks.Task<string> DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ITFinalAjaxDBService/GetItemDetailAll", ReplyAction="urn:ITFinalAjaxDBService/GetItemDetailAllResponse")]
        string GetItemDetailAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ITFinalAjaxDBService/GetItemDetailAll", ReplyAction="urn:ITFinalAjaxDBService/GetItemDetailAllResponse")]
        System.Threading.Tasks.Task<string> GetItemDetailAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ITFinalAjaxDBService/GetItemDetailById", ReplyAction="urn:ITFinalAjaxDBService/GetItemDetailByIdResponse")]
        ITFinalConsumeWCFService.ITFinalAjaxDBService.ItemDetail GetItemDetailById(int itemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ITFinalAjaxDBService/GetItemDetailById", ReplyAction="urn:ITFinalAjaxDBService/GetItemDetailByIdResponse")]
        System.Threading.Tasks.Task<ITFinalConsumeWCFService.ITFinalAjaxDBService.ItemDetail> GetItemDetailByIdAsync(int itemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ITFinalAjaxDBService/UpdateItemDetail", ReplyAction="urn:ITFinalAjaxDBService/UpdateItemDetailResponse")]
        string UpdateItemDetail(int itemID, string itemName, string itemMake, string itemSpec);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ITFinalAjaxDBService/UpdateItemDetail", ReplyAction="urn:ITFinalAjaxDBService/UpdateItemDetailResponse")]
        System.Threading.Tasks.Task<string> UpdateItemDetailAsync(int itemID, string itemName, string itemMake, string itemSpec);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITFinalAjaxDBServiceChannel : ITFinalConsumeWCFService.ITFinalAjaxDBService.ITFinalAjaxDBService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TFinalAjaxDBServiceClient : System.ServiceModel.ClientBase<ITFinalConsumeWCFService.ITFinalAjaxDBService.ITFinalAjaxDBService>, ITFinalConsumeWCFService.ITFinalAjaxDBService.ITFinalAjaxDBService {
        
        public TFinalAjaxDBServiceClient() {
        }
        
        public TFinalAjaxDBServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TFinalAjaxDBServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFinalAjaxDBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFinalAjaxDBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task<string> DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string GetItemDetailAll() {
            return base.Channel.GetItemDetailAll();
        }
        
        public System.Threading.Tasks.Task<string> GetItemDetailAllAsync() {
            return base.Channel.GetItemDetailAllAsync();
        }
        
        public ITFinalConsumeWCFService.ITFinalAjaxDBService.ItemDetail GetItemDetailById(int itemID) {
            return base.Channel.GetItemDetailById(itemID);
        }
        
        public System.Threading.Tasks.Task<ITFinalConsumeWCFService.ITFinalAjaxDBService.ItemDetail> GetItemDetailByIdAsync(int itemID) {
            return base.Channel.GetItemDetailByIdAsync(itemID);
        }
        
        public string UpdateItemDetail(int itemID, string itemName, string itemMake, string itemSpec) {
            return base.Channel.UpdateItemDetail(itemID, itemName, itemMake, itemSpec);
        }
        
        public System.Threading.Tasks.Task<string> UpdateItemDetailAsync(int itemID, string itemName, string itemMake, string itemSpec) {
            return base.Channel.UpdateItemDetailAsync(itemID, itemName, itemMake, itemSpec);
        }
    }
}
